### ISSUE TITLE
SystemTable not in types.rs?

### ISSUE THREAD

**Issue by WarpspeedSCP** [reynoldsbd/libefi#1]
I was following the rust OS tutorial by phil-opp, and wanted to try implementing a UEFI only system. but,  when I tried setting up the code as per the instructions on  the readme, I found that `SystemTable` was not declared in `types.rs`. Trying to compile gave me this error - 

```
error[E0432]: unresolved import `efi::types::SystemTable`
 --> src/main.rs:9:5
  |
9 |     SystemTable,
  |     ^^^^^^^^^^^ no `SystemTable` in `types`
```

**Comment by reynoldsbd** [comment]
Sorry about that! `SystemTable` is now at the root of the crate (since it's more than just a type, it's the root of the whole API). I will update the Readme to reflect this change!

In the meantime, you can fix this by changing your import to the following:

```rust
use efi::SystemTable;
```

**Comment by WarpspeedSCP** [comment]
Yup, works!
